# Generated by Django 5.1.3 on 2024-11-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('linked', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('A Fazer', 'A Fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default='A Fazer', max_length=50)),
            ],
        ),
    ]
